name: Deploy Statiq.Web Site
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet run -- deploy -l:verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
